### ISSUE TITLE
Error when calling bookmark-set: local 'tables' nil

### ISSUE THREAD

**Issue by jdsutherland** [nimatrueway/mpv-bookmark-lua-script#1]
When I attempt to trigger any n of of bookmark-set, I get the following error. I'm on OSX 10.11.

Lua error: /Users/x/.config/mpv/scripts/bookmarker.lua:85: attempt to get length of local 'tables' (a nil value)

**Comment by nimatrueway** [comment]
Could you attach your `bookmarks.json` file here ?
( it is located in `~/.config/mpv/bookmarks.json` )

**Comment by jdsutherland** [comment]
@nimatrueway Sorry - it seems to be working.

I remember originally getting an error that `bookmarks.json` didn't exist so I created it with `touch`
and then received the above error. After trying again the next morning (and deleting `bookmarks.json`), bookmark-set creates a valid `bookmarks.json` and all is well.

Sorry for the false report. Thanks for sharing this awesome script - super useful! Cheers.
