### ISSUE TITLE
Implement practical way to view bookmarks (and keys)

### ISSUE THREAD

**Issue by jdsutherland** [nimatrueway/mpv-bookmark-lua-script#2]
I think this script would be even more useful if there was a way to view stored bookmarks inside mpv. I'm thinking something similar to [Mpv-Playlistmanager](https://github.com/donmaiq/Mpv-Playlistmanager):

 ![](https://thumbs.gfycat.com/GiganticScaredEasternnewt-size_restricted.gif)

I'd submit a PR once finished if you'd be interested.

**Comment by nimatrueway** [comment]
Great idea 👍 
I am waiting for your PR. By the way if you needed a hand let me know.
