### ISSUE TITLE
'platform_independent' (a nil value) error while retrieving BM

### ISSUE THREAD

**Issue by tagwint** [nimatrueway/mpv-bookmark-lua-script#3]
Where **platform_independent** function supposed to come from please?
Setting BM seem to work, json file is created, but when trying to retrieve BM I am getting 

[bookmarker] Lua error: /home/user/.config/mpv/scripts/bookmarker.lua:122: attempt to call global 'platform_independent' (a nil value)

mpv version:
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.6

linux version
Linux host 4.15.4-300.fc27.x86_64 #1 SMP Mon Feb 19 23:31:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nimatrueway** [comment]
Oops, sorry. I mistakenly had removed this function. Now I put it back there.
By the way can I ask you a question, how did you get this clear nice error message of the script?
