### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vladislav-moshnin** [nimatrueway/mpv-bookmark-lua-script#4]
Hello. It does not work for me
![screenshot from 2018-09-16 15-28-25](https://user-images.githubusercontent.com/29102877/45594547-f59a6680-b9c6-11e8-81a8-d4634f7b5959.png)

At the same time the mpv-locatefile works fine
Help me please ;)

**Comment by nimatrueway** [comment]
Hi @hello-Vladislav !
Sorry, I fixed the error.

**Comment by vladislav-moshnin** [comment]
Thank you very much!
