### ISSUE TITLE
Win xp doesn't work

### ISSUE THREAD

**Issue by Dimsok** [nimatrueway/mpv-bookmark-lua-script#5]
I did try to save bookmark, but it only create file with [ ]. Is there any solution?

**Comment by nimatrueway** [comment]
Can you post your:

1. Input configuration file. (the lines relevant to bookmarker)
2. Run mpv in command line (e.g. `mpv {path-to-a-video-file}`), try to save a bookmark. And post your console here so that we can see if there has been an error in the script.

**Comment by Dimsok** [comment]
1. Ctrl+1 script_message bookmark-set  1
2. In cmd window i can't see nothing from bookmarker script after saving bookmark file (with [ ] content again).

**Comment by nimatrueway** [comment]
Do you see "Bookmark#1 saved" OSD on your mpv ?

**Comment by Dimsok** [comment]
I do, and i see osd when i try to load it unsuccesfull

**Comment by nimatrueway** [comment]
Sorry, I didn't detect any sign that could help with the diagnosis.

By the way I admit that this script is not much robust with not much rigorous logging that could help diagnosis of peculiar cases. I welcome any merge request that could improve it.

**Comment by nimatrueway** [comment]
Still have this problem? you might wanna try new `master` I have added proper logging and fixed a few issues. Run `mpv` with `--msg-level='bookmarker=debug'` and I might be able to help you.
