### ISSUE TITLE
not working on debian linux

### ISSUE THREAD

**Issue by imnisp** [nimatrueway/mpv-bookmark-lua-script#6]
I have edited the input.conf file with the noted configuration and when I run mpv with --msg-level=all=v the output indicates the script *is* being found and loaded. When I press the chosen key bindings, the appropriate script_message *is* being displayed on the console however the bookmarks.json is *NOT* ever being created nor is the desired function being performed.
Any thoughts?

**Comment by nimatrueway** [comment]
Unfortunately, I have not coded this plugin with appropriate logging since I was not familiar with mpv scripting tools when I started. I'll spend sometime on it tomorrow.

Meanwhile I'd suggest you to take `getConfigFile()` method (line 96) and replace the body with hardcoded the path to `bookmarks.json` file where you are sure that your app has read/write access to. Like:

```
function getConfigFile()
  return "{path}/bookmarks.json"
end
```

**Comment by nimatrueway** [comment]
I weaved some loggings into the code, update your `bookmarker.lua` to new master then run `mpv` with `--msg-level='bookmarker=debug'` parameter. I might be able to help you if you provide me the logs.

**Comment by imnisp** [comment]
Good Day,
 Thank you kindly for your efforts. I have updated to the new master and then ran mpv with the appropriate --msg-level.
Below is what was sent to the console when I pressed the key specified in the input.conf:

[bookmarker] [interface] received 'bookmark-set(1)' script message. 
[bookmarker] [persistence] config file is set to '/home/isp/.config/mpv/bookmarks.json'. 
[bookmarker] [persistence] bookmark file successfully loaded. length: 0 
[bookmarker] 
[bookmarker] stack traceback:
[bookmarker]    [C]: in function 'pairs'
[bookmarker]    /home/isp/.config/mpv/scripts/bookmarker.lua:61: in function 'tableLength'
[bookmarker]    /home/isp/.config/mpv/scripts/bookmarker.lua:71: in function 'loadTable'
[bookmarker]    /home/isp/.config/mpv/scripts/bookmarker.lua:246: in function 'handler'
[bookmarker]    mp.defaults:316: in function 'handler'
[bookmarker]    mp.defaults:418: in function 'call_event_handlers'
[bookmarker]    mp.defaults:454: in function 'dispatch_events'
[bookmarker]    mp.defaults:411: in function <mp.defaults:410>
[bookmarker]    [C]: in ?
[bookmarker]    [C]: in ?
[bookmarker] Lua error: /home/isp/.config/mpv/scripts/bookmarker.lua:61: bad argument #1 to 'pairs' (table expected, got nil)
[bookmarker] Exiting...

Virtually,
Doug McDowall

**Comment by nimatrueway** [comment]
Good day!
My pleasure, I always had it in mind to add proper logging to bookmarker, this was a good opportunity to add it. I think I had a good guess of what's missing based on your logs, try new `master` again please. Hopefully that fixes the problem.

**Comment by imnisp** [comment]
Hello,
 my apologies but below is the output from the new "main":

[bookmarker] [persistence] could not load bookmark file! 
[bookmarker] 
[bookmarker] stack traceback:
[bookmarker]    /home/isp/.config/mpv/scripts/bookmarker.lua:198: in function 'currentPositionAsBookmark'
[bookmarker]    /home/isp/.config/mpv/scripts/bookmarker.lua:257: in function 'handler'
[bookmarker]    mp.defaults:316: in function 'handler'
[bookmarker]    mp.defaults:418: in function 'call_event_handlers'
[bookmarker]    mp.defaults:454: in function 'dispatch_events'
[bookmarker]    mp.defaults:411: in function <mp.defaults:410>
[bookmarker]    [C]: in ?
[bookmarker]    [C]: in ?
[bookmarker] Lua error: /home/isp/.config/mpv/scripts/bookmarker.lua:198: attempt to call field 'format_json' (a nil value)

Two observations if they are of any significance:

1) if the json file(*) does not exist, it is not automatically created
2) if I 'touch' create an empty file of the same name, I still get the
   errors above.

I have confirmed propers permission to the path destination of the json.

Virtually,
Douglas McDowall

(*) path = os.getenv("HOME") .. "/.config/mpv/bookmarks.json"

**Comment by nimatrueway** [comment]
Seems like your mpv does not support `utils.format_json`. Would you please send your `mpv --version` output? Also upgrade to latest `mpv` and verify that this problem is not due to old mpv version.

**Comment by imnisp** [comment]
mpv --version
mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Tue Mar 17 06:56:30 UTC 2015
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

**Comment by imnisp** [comment]
hopefully an update isn't necessary since updating mpv is not an option for this box

**Comment by nimatrueway** [comment]
`utils.format_json(v)` was added exactly 5 years ago.
https://github.com/mpv-player/mpv/blame/master/DOCS/man/lua.rst

**Comment by nimatrueway** [comment]
I'm afraid I can't change this plugin too profoundly, I can't confirm if it works okay with this workaround but try replacing `utils.format_json` to `utils.to_string` see if it works.
