### ISSUE TITLE
I was only able to set Bookmarks using Strg-1 and Strg-2 

### ISSUE THREAD

**Issue by paralion** [nimatrueway/mpv-bookmark-lua-script#7]
3,4,5... didnt work, json file remained the same, too. 
Do I need the latest version of mpv player? 

Another Question: I am looking for a solution that allows me to quickly access the shortcuts also in 2-digit (or even 3) numbers via keyboard. Will **Alt-12** or even **Alt-123**  work?

**Comment by nimatrueway** [comment]
If you need my help, provide me with enough information as suggested in here:

https://github.com/nimatrueway/mpv-bookmark-lua-script#bug-reporting

**Comment by nimatrueway** [comment]
Any standard shortcut could be assigned, but [`Alt+1` then `Alt+2`] is not a shortcut but a sequence of shortcuts, so I'm afraid it requires a large effort that I can't afford now.
